org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.255
neo_version_range=[21.1.200, 21.2)
loader_version_range=[1,)
mod_id=life_crystal
mod_license=MIT License
mod_version=1.0.0-1.21.1NeoForge
mod_group_id=qjend.lifecrystal